// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOPhGYtQkmiHe46ApgtSQA_qRhdaaGr_s',
    appId: '1:484169081903:web:125402174564a0097d12da',
    messagingSenderId: '484169081903',
    projectId: 'sungka-game-82b89',
    authDomain: 'sungka-game-82b89.firebaseapp.com',
    storageBucket: 'sungka-game-82b89.firebasestorage.app',
    measurementId: 'G-DTTPGX6S6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3w_94LrqF5e78nx_XuGF5RQyenjhqgeU',
    appId: '1:484169081903:android:bc1a78ce3abb15fc7d12da',
    messagingSenderId: '484169081903',
    projectId: 'sungka-game-82b89',
    storageBucket: 'sungka-game-82b89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlYjcbQEJcMBN2qo2FpoOSeJUimmnu2vM',
    appId: '1:484169081903:ios:5350ec5456e133b57d12da',
    messagingSenderId: '484169081903',
    projectId: 'sungka-game-82b89',
    storageBucket: 'sungka-game-82b89.firebasestorage.app',
    iosBundleId: 'com.example.sungka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlYjcbQEJcMBN2qo2FpoOSeJUimmnu2vM',
    appId: '1:484169081903:ios:5350ec5456e133b57d12da',
    messagingSenderId: '484169081903',
    projectId: 'sungka-game-82b89',
    storageBucket: 'sungka-game-82b89.firebasestorage.app',
    iosBundleId: 'com.example.sungka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOPhGYtQkmiHe46ApgtSQA_qRhdaaGr_s',
    appId: '1:484169081903:web:1d057bc0d10dabeb7d12da',
    messagingSenderId: '484169081903',
    projectId: 'sungka-game-82b89',
    authDomain: 'sungka-game-82b89.firebaseapp.com',
    storageBucket: 'sungka-game-82b89.firebasestorage.app',
    measurementId: 'G-ZT57Z9H6Y0',
  );
}
